export const USER_DOES_NOT_EXIST = 'USER_DOES_NOT_EXIST'
export const USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS'
export const INVALID_USERNAME_CHARACTERS = 'INVALID_USERNAME_CHARACTERS'
export const USERNAME_TOO_LONG = 'USERNAME_TOO_LONG'